apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: finance
type: Opaque
stringData:
  root-username: admin
  root-password: changeme-root
  app-username: finance
  app-password: changeme-app