apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: finance
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
    - name: otlp-http
      port: 4318